# Generated by Django 4.2.7 on 2023-11-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseofoil',
            options={'verbose_name': 'База', 'verbose_name_plural': 'Базы'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250, verbose_name='Компания')),
                ('surname', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('middleName', models.CharField(max_length=250, verbose_name='Отчество')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('tel', models.CharField(max_length=250, verbose_name='Телефон')),
                ('mail', models.CharField(max_length=250, verbose_name='Почта')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.baseofoil')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
