# Generated by Django 4.2.7 on 2023-11-17 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOfOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('buildDate', models.DateField(verbose_name='Год постройки')),
                ('tel', models.CharField(max_length=250, verbose_name='Телефон')),
                ('dayOfWork', models.CharField(max_length=250, verbose_name='Рабочие дни')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('middleName', models.CharField(max_length=250, verbose_name='Отчество')),
                ('birthDate', models.DateField(verbose_name='Дата рождение')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('tel', models.CharField(max_length=250, verbose_name='Телефон')),
                ('mail', models.CharField(max_length=250, verbose_name='Почта')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.baseofoil')),
            ],
        ),
    ]
